develop:
	HOBBIT_RABBIT_HOST=localhost \
	KEYCLOAK_DIRECT_URL=http://localhost:8181/auth \
	KEYCLOAK_AUTH_URL=http://localhost:8181/auth \
	CHECK_REALM_URL=false \
	mvn jetty:run -Djetty.http.port=8080 #-Dorg.eclipse.jetty.LEVEL=DEBUG
