apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
    labels:
        app: rabbitmq
spec:
    selector:
        app: rabbitmq
    ports:
        - name: amqp
          port: 5672   # Exposes AMQP port inside the cluster
          targetPort: 5672
        - name: management
          port: 15672  # Exposes the Management UI inside the cluster
          targetPort: 15672
    type: ClusterIP  # Internal access only
