apiVersion: v1
kind: PersistentVolume
metadata:
    name: virtuoso-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain # or Delete, as needed
    storageClassName: "" # Important: Leave empty if not using Storage Classes
    nfs:
        server: 131.234.29.64 # Your NFS server IP
        path: /data/nfs/kubedata/virtuoso # The path to your exported NFS share
