apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: virtuoso-pvc
    labels:
        app: virtuoso
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
