apiVersion: apps/v1
kind: Deployment
metadata:
    name: virtuoso
    labels:
        app: virtuoso
spec:
    replicas: 1
    selector:
        matchLabels:
            app: virtuoso
    template:
        metadata:
            labels:
                app: virtuoso
        spec:
            securityContext:  # This is the correct place for fsGroup
                  fsGroup: 1000
            containers:
                - name: virtuoso
                  image: hobbitproject/virtuoso_opensource:v07.20.3217
                  securityContext:
                     runAsUser: 79184 # Replace with the actual numeric user ID
                     runAsGroup: 10000
                  ports:
                      - containerPort: 8890  # HTTP (SPARQL endpoint)
                      - containerPort: 1111  # ISQL (command-line interface)
                  env:
                      - name: VIRTUOSO_DBNAME
                        value: "virtuoso"
                      - name: VIRTUOSO_USER
                        value: "dba"
                      - name: VIRTUOSO_PASSWORD
                        value: "dba"
                  volumeMounts:
                      - mountPath: /opt/virtuoso-opensource/database
                        name: virtuoso-storage
            volumes:
                - name: virtuoso-storage
                  persistentVolumeClaim:
                      claimName: virtuoso-pvc
