apiVersion: v1
kind: Service
metadata:
    name: virtuoso-service
    labels:
        app: virtuoso
spec:
    selector:
        app: virtuoso
    ports:
        - protocol: TCP
          port: 8890
          targetPort: 8890
          name: sparql
          nodePort: 31001
        - protocol: TCP
          port: 1111
          targetPort: 1111
          name: isql
    type: NodePort
