apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    labels:
        app: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: redis:6.2.6
                  securityContext:
                      runAsUser: 79184 # Replace with the actual numeric user ID
                      runAsGroup: 10000
                  ports:
                      - containerPort: 6379
                  volumeMounts:
                      - mountPath: /data
                        name: redis-storage
            volumes:
                - name: redis-storage
                  persistentVolumeClaim:
                      claimName: redis-pvc
