apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: controller-pvc
    labels:
        app: controller
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
