apiVersion: v1
kind: Service
metadata:
    name: controller-service
    labels:
        app: controller
spec:
    selector:
        app: controller
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
    type: ClusterIP  # Change to LoadBalancer or NodePort if needed
