apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: node-pod-service-reader
    namespace: default
rules:
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["create", "get", "update", "delete", "list", "watch"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["create", "get", "update", "delete", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: my-service-account-binding
    namespace: default
subjects:
    - kind: ServiceAccount
      name: controller-service
      namespace: default
roleRef:
    kind: Role
    name: node-pod-service-reader
    apiGroup: rbac.authorization.k8s.io
