apiVersion: v1
kind: PersistentVolume
metadata:
    name: enexa-metadata-pv
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: ""
    nfs:
        server: 131.234.29.64
        path: "/data/nfs/kubedata/enexametadata"
