apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: enexa-metadata-pvc
    labels:
        app: enexa-metadata
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
