apiVersion: v1
kind: Pod
metadata:
  name: riak-debug-pod
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
  containers:
  - name: debug-container
    image: git.project-hobbit.eu:4567/gitadmin/basho-riak-kv:1.0.1
    stdin: true
    tty: true
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      runAsGroup: 0
