version: '3.3'
services:
  platform-controller:
    image: hobbitproject/hobbit-platform-controller:dev
    networks:
      - hobbit
      - hobbit-core
    environment:
      HOBBIT_RABBIT_IMAGE: "rabbitmq:management"
      HOBBIT_RABBIT_HOST: "rabbit"
      HOBBIT_REDIS_HOST: "redis"
      DEPLOY_ENV: "develop"
      GITLAB_USER: "${GITLAB_USER}"
      GITLAB_EMAIL: "${GITLAB_EMAIL}"
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      #LOGGING_GELF_ADDRESS: "udp://localhost:12201"
      SWARM_NODE_NUMBER: "1"
      PROMETHEUS_HOST: prometheus
      PROMETHEUS_PORT: 9090
      USE_GITLAB: "false"
      LOCAL_METADATA_DIRECTORY: "/metadata"
      DOCKER_AUTOPULL: "0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./metadata:/metadata

  # HOBBIT GUI
  gui:
    image: hobbitproject/hobbit-gui:dev
    ports:
      - "8080:8080"
    networks:
      - hobbit-core
      - hobbit
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      #- KEYCLOAK_AUTH_URL=http://192.168.99.100:8181/auth
      - KEYCLOAK_AUTH_URL=http://localhost:8181/auth
      - CHECK_REALM_URL=false
      - KEYCLOAK_DIRECT_URL=http://keycloak:8080/auth
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_HTTP_PORT=9200
      - USE_UI_AUTH=false
    #volumes:
      #- /data/docker/messages/global.html:/var/lib/jetty/webapps/messages/global.html
      #- /data/docker/messages/benchmark.html:/var/lib/jetty/webapps/messages/benchmark.html
      #- /data/docker/messages/status.html:/var/lib/jetty/webapps/messages/status.html

  # Keycloak user management (used by the GUI)
  # keycloak:
  #   image: hobbitproject/hobbit-keycloak:latest
  #   ports:
  #     - "8181:8080"
  #   networks:
  #     - hobbit
  #   volumes:
  #     - ./config/keycloak:/opt/jboss/keycloak/standalone/data/db

  # HOBBIT Analysis component
  analysis:
    image: hobbitproject/hobbit-analysis-component:dev
    networks:
      - hobbit-core
    environment:
      - HOBBIT_RABBIT_HOST=rabbit

  # message bus
  rabbit:
    image: rabbitmq:management
    networks:
      - hobbit
      - hobbit-core
    ports:
      - "8081:15672"
      # Forwarding the port for testing
      - "5672:5672"

  # DB for controller
  redis:
    image: redis:4.0.7
    volumes:
      - ./config/redis-db:/data
    command: ["redis-server", "/data/redis.conf"]
    networks:
      - hobbit-core
    ports:
      # Forwarding the port for tests
      - "6379:6379"

  # Triple store
  vos:
    image: hobbitproject/virtuoso_opensource:v07.20.3217
    hostname: vos
    container_name: vos
    stop_signal: SIGINT
    stop_grace_period: 2m
    volumes:
      - ./config/db:/opt/virtuoso-opensource/var/lib/virtuoso/db
      #- ./config/db:/opt/virtuoso-opensource/database
    networks:
      - hobbit-core
    ports:
      - "8890:8890"

  # Storage service
  storage-service:
    image: hobbitproject/hobbit-storage-service:dev
    networks:
      - hobbit-core
    environment:
      - SPARQL_ENDPOINT_URL=http://vos:8890/sparql
      - HOBBIT_RABBIT_HOST=rabbit
      - SPARQL_ENDPOINT_USERNAME=dba
      - SPARQL_ENDPOINT_PASSWORD=dba

  node-exporter:
    image: prom/node-exporter
    networks:
      - hobbit-core

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    networks:
      - hobbit-core
    volumes:
      - /:/rootfs:ro
      - /dev/disk:/dev/disk:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run:/var/run:rw

  prometheus:
    image: prom/prometheus
    networks:
      - hobbit-core
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/config:ro
    command: --config.file=/config/prometheus.conf
    depends_on:
      - node-exporter
      - cadvisor

networks:
  hobbit:
    external:
      name: hobbit
  hobbit-core:
    external:
      name: hobbit-core
