apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: hobbit
spec:
  cidr: 172.16.100.0/24
  vxlanMode: Always
  natOutgoing: true
  disabled: false
  nodeSelector: all()

---

apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: hobbit-core
spec:
  cidr: 172.16.101.0/24
  vxlanMode: Always
  natOutgoing: true
  disabled: false
  nodeSelector: all()

---

apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: hobbit-services
spec:
  cidr: 172.16.102.0/24
  vxlanMode: Always
  natOutgoing: true
  disabled: false
  nodeSelector: all()
