FROM openlink/virtuoso_opensource:v07.20.3217-base

ENV VIRT_HOME /opt/virtuoso-opensource
ENV VIRT_DB /opt/virtuoso-opensource/database

RUN export PATH=$PATH:/opt/virtuoso-opensource/bin

EXPOSE 1111
EXPOSE 8890

WORKDIR $VIRT_DB
CMD /opt/virtuoso-opensource/bin/virtuoso-t -f
