name: make
on: push
jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/setup-node@v2
      with:
        node-version: 8
    - run: |
        docker swarm init
    - run: make test
